### PR TITLE
added details about submodules usage

### PR DESCRIPTION
**Pull request by mbravorus**

### CODE REVIEW

**Comment by alterNERDtive** [comment]
`git submodule update --remote` is actually not the thing you want to use. It sets the submodule working copy to the remote-tracking branch.

What you _actually_ need to do is `git fetch` from within the submodule, then run a `git submodule update` on the main repo.

As long as there are no compatibility-breaking changes on the submodule remote, both work fine though.

**Comment by mbravorus** [comment]
If you are just a user, you probably want exactly the remote tracking branch. and for people who want to contribute, there's usually some kind of CONTRIBUTING.md :)

Ultimately, I wanted to add a minimum set of instructions for an arbitrary user to get the tools working. Happy to amend the way you see it best.

**Comment by alterNERDtive** [comment]
> If you are just a user, you probably want exactly the remote tracking branch

See, that’s not true. Right now it’s ahead of the commit used here, for example. Now that _should_ not break it, but won’t be guaranteed not to.

And if you are “just a user”, you probably just want to grab a release anyway (incidentally there now is one).

**Comment by alterNERDtive** [comment]
I guess I’m just going to add something pointing people to the releases page …

**Pull request closed without merging**
